---

- name: "01.1 - make sure 'overlay' kernel module is loaded"
  modprobe:
    name: overlay
    state: present
  notify:
    - docker-stop-service
    - docker-clear-data-dir

- meta: flush_handlers

- name: "01.2 - make sure docker daemon config directory exists"
  file:
    path: "{{ __docker_daemon_config_dir }}"
    state: directory
  become: yes
