---

- name: "02.1 - install prerequisite packages"
  apt:
    name: "{{ __docker_prerequisite_packages|select()|list }}"
    state: present
  become: yes

- name: "02.2.1 - install some of docker packages"
  apt:
    deb: "{{ item }}"
    state: present
  become: yes
  loop:
    - "{{ __docker_containerd_download_url }}"
    - "{{ __docker_cli_download_url }}"

- name: "02.2.2 - install docker package"
  apt:
    deb: "{{ item }}"
    state: present
  become: yes
  ignore_errors: yes
  loop:
    - "{{ __docker_download_url }}"

- name: "02.2.3 - fix broken installation"
  apt:
    state: fixed
  become: yes
