---

- name: "02.1 - install prerequisite packages"
  apt:
    name: "{{ __docker_prerequisite_packages|select()|list }}"
    state: present
  become: yes

- name: "02.2 - download docker packages"
  get_url:
    url: "{{ item }}"
    dest: "{{ __docker_play_dir }}/{{ item | urlsplit('path') | basename }}"
  loop:
    - "{{ __docker_containerd_download_url }}"
    - "{{ __docker_cli_download_url }}"
    - "{{ __docker_download_url }}"

- name: "02.3.1 - install some of docker packages"
  apt:
    deb: "{{ __docker_play_dir }}/{{ item | urlsplit('path') | basename }}"
    state: present
  become: yes
  loop:
    - "{{ __docker_containerd_download_url }}"
    - "{{ __docker_cli_download_url }}"

- name: "02.3.2 - install docker daemon package"
  apt:
    deb: "{{ __docker_play_dir }}/{{ __docker_download_url | urlsplit('path') | basename }}"
    state: present
  become: yes
  ignore_errors: yes

- name: "02.4 - fix broken installation"
  apt:
    state: fixed
  become: yes
