---

- name: "02.1 - install prerequisite packages"
  apt:
    name: "{{ __docker_prerequisite_packages|select()|list }}"
    state: present
  become: yes

- name: "02.2 - install docker packages"
  apt:
    deb: "{{ item }}"
    state: present
  become: yes
  loop:
    - "{{ __docker_containerd_download_url }}"
    - "{{ __docker_download_url }}"
    - "{{ __docker_cli_download_url }}"
