---

- name: "docker-clear-data-dir"
  file:
    path: "{{ __docker_data_dir }}"
    state: absent
  become: yes

- name: "docker-reload-systemd"
  shell:
    cmd: "systemctl daemon-reload"
  args:
    warn: no
  become: yes

- name: "docker-stop-service"
  service:
    name: "{{ __docker_service_name }}"
    state: stopped
  become: yes
  # might be not installed yet
  ignore_errors: yes

- name: "docker-restart-service"
  service:
    name: "{{ __docker_service_name }}"
    state: restarted
  become: yes
